version: '3.8'

services:
  prometheus:
    image: prom/prometheus
    container_name: promethues
    command:
      # With this setting, the default Prometheus.yml is set.
      # You can change the route you want.
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
    - 9090:9090
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
    - 8080:8080
    depends_on:
      - redis
  redis:
    image: redis
    container_name: redis
    ports:
    - 6379:6379
  # TODO: Node Exporter, PostgresSQL Exporter, MySQL Exporter
  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    command:
      - '--path.rootfs=/host'
    network_mode: host
    pid: host
    restart: unless-stopped
  postgres-exporter:
    image: quay.io/prometheuscommunity/postgres-exporter
    ports:
    - 9187:9187
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
    - 3000:3000
